version: '3'

services:
  database:
    env_file: .
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_USER: $PG_USER
      POSTGRES_DB: $PG_DB_NAME
      restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql

  bot:
    container_name: qrbot
    build: .
    volumes:
      - .:/src
    restart: always
    depends_on:
      - database


